import {
  BadgeCheck,
  Boxes,
  ClipboardList,
  IndianRupee,
  PackageCheck,
  RotateCcw,
  Truck,
} from "lucide-react";
import type { InventoryItem, OnboardingProgress, SellerMetric, SellerNotification, SellerOrder, SellerProduct } from "./types";

export const sellerProfile = {
  storeName: "Freshline Local",
  owner: "Akash Kumar",
  zone: "Indiranagar 2 km service zone",
  category: "Daily essentials and fresh foods",
  rating: "4.7",
  verification: "Store profile verified",
  operatingState: "Accepting orders",
  fulfillmentHealth: "96% on-time handoffs",
};

export const sellerMetrics: SellerMetric[] = [
  { label: "Orders today", value: "42", helper: "11 need action now", tone: "warning", icon: ClipboardList },
  { label: "Pending fulfillment", value: "9", helper: "3 at SLA risk", tone: "danger", icon: PackageCheck },
  { label: "Low stock products", value: "7", helper: "2 likely to stock out today", tone: "warning", icon: Boxes },
  { label: "Revenue placeholder", value: "Rs 82,450", helper: "Settlement engine not connected", tone: "neutral", icon: IndianRupee },
  { label: "Cancellation placeholder", value: "1.8%", helper: "Policy tracking placeholder", tone: "success", icon: RotateCcw },
  { label: "Fulfillment rate", value: "96%", helper: "Based on mock operational queue", tone: "success", icon: Truck },
];

export const products: SellerProduct[] = [
  {
    id: "prod-paneer-200",
    sku: "FRL-DAIRY-PNR-200",
    name: "Farm Fresh Paneer 200g",
    category: "Dairy",
    price: 128,
    mrp: 145,
    status: "published",
    visibility: "marketplace",
    stock: 14,
    reserved: 5,
    lowStockThreshold: 10,
    soldToday: 31,
    imageHint: "Paneer pack",
    updatedAt: "Today 09:10",
  },
  {
    id: "prod-tomato-1kg",
    sku: "FRL-VEG-TOM-1KG",
    name: "Organic Tomato Pack 1kg",
    category: "Fresh vegetables",
    price: 89,
    mrp: 99,
    status: "published",
    visibility: "marketplace",
    stock: 8,
    reserved: 3,
    lowStockThreshold: 12,
    soldToday: 46,
    imageHint: "Tomatoes",
    updatedAt: "Today 08:42",
  },
  {
    id: "prod-oil-groundnut",
    sku: "FRL-OIL-GNT-1L",
    name: "Cold Pressed Groundnut Oil 1L",
    category: "Grocery",
    price: 340,
    mrp: 375,
    status: "published",
    visibility: "marketplace",
    stock: 27,
    reserved: 4,
    lowStockThreshold: 8,
    soldToday: 12,
    imageHint: "Oil bottle",
    updatedAt: "Yesterday 18:20",
  },
  {
    id: "prod-bread-sourdough",
    sku: "FRL-BAK-SOUR-450",
    name: "Whole Wheat Sourdough 450g",
    category: "Bakery",
    price: 160,
    mrp: 180,
    status: "published",
    visibility: "store_only",
    stock: 0,
    reserved: 0,
    lowStockThreshold: 6,
    soldToday: 18,
    imageHint: "Bread loaf",
    updatedAt: "Today 07:35",
  },
  {
    id: "prod-millet-mix",
    sku: "FRL-BRK-MLT-500",
    name: "Millet Breakfast Mix 500g",
    category: "Breakfast",
    price: 210,
    mrp: 230,
    status: "draft",
    visibility: "hidden",
    stock: 36,
    reserved: 0,
    lowStockThreshold: 10,
    soldToday: 0,
    imageHint: "Millet pack",
    updatedAt: "Draft saved 11:12",
  },
  {
    id: "prod-coffee-filter",
    sku: "FRL-BEV-COF-250",
    name: "Filter Coffee Blend 250g",
    category: "Beverages",
    price: 290,
    mrp: 320,
    status: "archived",
    visibility: "hidden",
    stock: 4,
    reserved: 0,
    lowStockThreshold: 8,
    soldToday: 0,
    imageHint: "Coffee pouch",
    updatedAt: "Archived 2 days ago",
  },
];

export const inventory: InventoryItem[] = products.map((product, index) => ({
  ...product,
  aisle: ["Cold shelf A2", "Fresh bin V1", "Dry rack G4", "Bakery crate B1", "Dry rack B7", "Back shelf C2"][index],
  batch: ["PNR-M25-14", "TOM-KR-2105", "GNT-0426-B", "SOUR-M25-2", "MLT-MAY-77", "COF-0426-X"][index],
  expiry: ["2026-05-27", "2026-05-26", "2026-11-12", "2026-05-25", "2026-09-05", "2026-08-18"][index],
  lastMovement: ["Reserved 5 for active orders", "Stock adjusted after morning intake", "12 sold across 6 orders", "Marked out of stock", "Draft product stock loaded", "Archived item retained for audit"][index],
}));

export const orders: SellerOrder[] = [
  {
    id: "KX-1042",
    customer: "Ananya Kumar",
    phone: "+91 98765 21011",
    address: "12th Main, Indiranagar, Bengaluru",
    status: "processing",
    promisedInMinutes: 18,
    createdAt: "Today 10:42",
    paymentMode: "UPI",
    subtotal: 467,
    deliveryFee: 25,
    notes: "Customer requested firm tomatoes.",
    items: [
      { sku: "FRL-DAIRY-PNR-200", name: "Farm Fresh Paneer 200g", quantity: 2, unitPrice: 128, picked: true },
      { sku: "FRL-VEG-TOM-1KG", name: "Organic Tomato Pack 1kg", quantity: 1, unitPrice: 89, picked: false },
      { sku: "FRL-BAK-SOUR-450", name: "Whole Wheat Sourdough 450g", quantity: 1, unitPrice: 160, picked: true },
    ],
    timeline: [
      { label: "Order received", time: "10:42", state: "done" },
      { label: "Confirmed by seller", time: "10:44", state: "done" },
      { label: "Picking items", time: "Now", state: "current" },
      { label: "Pack and handoff", time: "Next", state: "next" },
    ],
  },
  {
    id: "KX-1043",
    customer: "Nisha Rao",
    phone: "+91 99807 44122",
    address: "CMH Road, near Metro Gate B",
    status: "pending",
    promisedInMinutes: 12,
    createdAt: "Today 10:50",
    paymentMode: "COD",
    subtotal: 718,
    deliveryFee: 25,
    notes: "High priority. First order from customer.",
    items: [
      { sku: "FRL-OIL-GNT-1L", name: "Cold Pressed Groundnut Oil 1L", quantity: 1, unitPrice: 340, picked: false },
      { sku: "FRL-BEV-COF-250", name: "Filter Coffee Blend 250g", quantity: 1, unitPrice: 290, picked: false },
      { sku: "FRL-VEG-TOM-1KG", name: "Organic Tomato Pack 1kg", quantity: 1, unitPrice: 89, picked: false },
    ],
    timeline: [
      { label: "Order received", time: "10:50", state: "done" },
      { label: "Seller confirmation", time: "Due now", state: "current" },
      { label: "Start processing", time: "Next", state: "next" },
    ],
  },
  {
    id: "KX-1044",
    customer: "Sanjay Menon",
    phone: "+91 98450 11223",
    address: "Defence Colony, 3rd Cross",
    status: "packed",
    promisedInMinutes: 31,
    createdAt: "Today 10:28",
    paymentMode: "Card",
    subtotal: 548,
    deliveryFee: 25,
    notes: "No substitution needed.",
    items: [
      { sku: "FRL-BRK-MLT-500", name: "Millet Breakfast Mix 500g", quantity: 1, unitPrice: 210, picked: true },
      { sku: "FRL-DAIRY-PNR-200", name: "Farm Fresh Paneer 200g", quantity: 1, unitPrice: 128, picked: true },
    ],
    timeline: [
      { label: "Order received", time: "10:28", state: "done" },
      { label: "Processed", time: "10:36", state: "done" },
      { label: "Packed", time: "10:44", state: "current" },
      { label: "Shipment preparation", time: "Placeholder", state: "next" },
    ],
  },
];

export const notifications: SellerNotification[] = [
  { id: "n1", type: "order", title: "New order awaiting confirmation", detail: "KX-1043 has 12 minutes before SLA risk.", time: "2 min ago", read: false },
  { id: "n2", type: "inventory", title: "Tomato pack crossed low-stock threshold", detail: "8 available, 3 reserved. Replenish before evening peak.", time: "18 min ago", read: false },
  { id: "n3", type: "admin", title: "Store policy review placeholder", detail: "Future admin alerts will appear here with action ownership.", time: "1 hr ago", read: true },
  { id: "n4", type: "payout", title: "Payout engine not connected", detail: "Settlement lifecycle is intentionally deferred to a later phase.", time: "Today 08:00", read: true },
];

export const onboardingProgress: OnboardingProgress[] = [
  { step: "business", label: "Business information", complete: true },
  { step: "branding", label: "Store branding", complete: true },
  { step: "verification", label: "Verification placeholders", complete: false },
  { step: "categories", label: "Seller categories", complete: true },
  { step: "complete", label: "Completion review", complete: false },
];

export const trustSignals = [
  { label: "Verification", value: sellerProfile.verification, icon: BadgeCheck },
  { label: "Fulfillment health", value: sellerProfile.fulfillmentHealth, icon: Truck },
  { label: "Operating state", value: sellerProfile.operatingState, icon: PackageCheck },
];
