/**
 * Canonical product ontology types (PP-3). The product master model binds PP-1 taxonomy and PP-2
 * brands to products, SKUs, variants and packaging — the layer every future product must conform to.
 */

/**
 * The full classification hierarchy (Phase 1). Upper levels are owned by PP-1 (taxonomy) and PP-2
 * (brand); PP-3 owns PRODUCT / SKU / VARIANT. INVENTORY_ITEM is defined here as the downstream leaf
 * but is populated only by later waves (PP-4+).
 */
export const PRODUCT_HIERARCHY_LEVELS = [
  "DEPARTMENT",
  "CATEGORY",
  "SUBCATEGORY",
  "FAMILY",
  "TYPE",
  "BRAND",
  "PRODUCT",
  "SKU",
  "VARIANT",
  "INVENTORY_ITEM",
] as const;
export type ProductHierarchyLevel = (typeof PRODUCT_HIERARCHY_LEVELS)[number];

export const PRODUCT_STATUSES = ["DRAFT", "ACTIVE", "ARCHIVED", "MERGED", "SPLIT"] as const;
export type ProductStatus = (typeof PRODUCT_STATUSES)[number];

export const PRODUCT_LIFECYCLE_STATUSES = ["PLANNED", "ACTIVE", "DISCONTINUED", "END_OF_LIFE"] as const;
export type ProductLifecycleStatus = (typeof PRODUCT_LIFECYCLE_STATUSES)[number];

export const SKU_NAMESPACES = ["INTERNAL", "VENDOR", "MARKETPLACE", "SUPPLIER"] as const;
export type SkuNamespace = (typeof SKU_NAMESPACES)[number];

export const BARCODE_STANDARDS = ["BARCODE", "UPC", "EAN", "GTIN"] as const;
export type BarcodeStandard = (typeof BARCODE_STANDARDS)[number];

export const PACKAGING_LEVELS = ["UNIT", "PACK", "MULTIPACK", "BOX", "CASE", "CARTON", "BUNDLE"] as const;
export type PackagingLevel = (typeof PACKAGING_LEVELS)[number];

/** Canonical variant axes (Phase 4). */
export const VARIANT_AXES = ["size", "weight", "volume", "flavor", "color", "pack_size", "material", "bundle", "configuration"] as const;
export type VariantAxis = (typeof VARIANT_AXES)[number];

export type AttributeValue = string | number | boolean;
export type AttributeMap = Record<string, AttributeValue>;
export type LocalizedText = Record<string, string>;

export interface PackagingSpec {
  level: PackagingLevel;
  /** Base selling unit, e.g. "ml", "g", "count". */
  baseUnit: string;
  /** Quantity of base unit in a single sellable unit (e.g. 500 for 500ml). */
  baseQuantity: number;
  /** Number of base units bundled at this packaging level (1 for a single unit). */
  unitsPerPack: number;
}

export interface VariantIdentifiers {
  vendorSku?: string;
  marketplaceSku?: string;
  supplierSku?: string;
  barcode?: string;
  upc?: string;
  ean?: string;
  gtin?: string;
}

export interface ProductVariant {
  id: string;
  productId: string;
  name: string;
  slug: string;
  axes: Record<string, AttributeValue>;
  /** Deterministic internal SKU generated by the SKU engine. */
  internalSku: string;
  identifiers: VariantIdentifiers;
  packaging: PackagingSpec;
  /** Variant-scope attribute overrides. */
  attributes: AttributeMap;
  sortOrder: number;
  status: ProductStatus;
  createdAt: string;
  updatedAt: string;
}

export interface ProductVariantInput {
  id?: string;
  name: string;
  slug?: string;
  axes?: Record<string, AttributeValue>;
  internalSku?: string;
  identifiers?: VariantIdentifiers;
  packaging?: Partial<PackagingSpec>;
  attributes?: AttributeMap;
  sortOrder?: number;
  status?: ProductStatus;
}

/** Canonical product master (Phase 2). */
export interface ProductMaster {
  id: string;
  name: string;
  slug: string;
  description: string;
  brandId: string | null;
  /** PP-1 taxonomy department slug (required — every product is classified). */
  departmentId: string;
  categoryId: string | null;
  familyId: string | null;
  typeId: string | null;
  status: ProductStatus;
  lifecycleStatus: ProductLifecycleStatus;
  version: number;
  /** Product-scope attribute values. */
  attributes: AttributeMap;
  localizedNames: LocalizedText;
  variants: ProductVariant[];
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
  mergedIntoId: string | null;
  metadata: Record<string, unknown>;
}

export interface ProductMasterInput {
  id?: string;
  name: string;
  slug?: string;
  description?: string;
  brandId?: string | null;
  departmentId: string;
  categoryId?: string | null;
  familyId?: string | null;
  typeId?: string | null;
  status?: ProductStatus;
  lifecycleStatus?: ProductLifecycleStatus;
  attributes?: AttributeMap;
  localizedNames?: LocalizedText;
  variants?: ProductVariantInput[];
  metadata?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------------------------
// Inheritance (Phase 6)
// ---------------------------------------------------------------------------------------------

export const INHERITANCE_SCOPES = ["GLOBAL", "TAXONOMY", "BRAND", "PRODUCT", "VARIANT"] as const;
export type InheritanceScope = (typeof INHERITANCE_SCOPES)[number];

export interface ResolvedProductAttribute {
  key: string;
  value: AttributeValue;
  scope: InheritanceScope;
  /** Lower-precedence values that were overridden, nearest-last. */
  overridden: { scope: InheritanceScope; value: AttributeValue }[];
}

export interface InheritanceConflict {
  key: string;
  reason: "LOCKED_OVERRIDE" | "UNKNOWN_ATTRIBUTE" | "INVALID_ENUM_VALUE";
  scope: InheritanceScope;
  detail?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------------------------
// Validation (Phase 12)
// ---------------------------------------------------------------------------------------------

export const PRODUCT_VALIDATION_CODES = [
  "DUPLICATE_SKU",
  "DUPLICATE_BARCODE",
  "BROKEN_VARIANT_TREE",
  "INHERITANCE_CONFLICT",
  "ORPHAN_PRODUCT",
  "INVALID_TAXONOMY_MAPPING",
  "INVALID_BRAND_MAPPING",
  "GOVERNANCE_VIOLATION",
  "DUPLICATE_PRODUCT_SLUG",
  "MISSING_VARIANT_SKU",
] as const;
export type ProductValidationCode = (typeof PRODUCT_VALIDATION_CODES)[number];

export type ProductValidationSeverity = "error" | "warning";

export interface ProductValidationIssue {
  code: ProductValidationCode;
  severity: ProductValidationSeverity;
  entityId: string | null;
  message: string;
  detail?: Record<string, unknown>;
}

export interface ProductValidationReport {
  valid: boolean;
  checkedProducts: number;
  checkedVariants: number;
  checkedSkus: number;
  errorCount: number;
  warningCount: number;
  issues: ProductValidationIssue[];
}

// ---------------------------------------------------------------------------------------------
// Governance (Phase 7)
// ---------------------------------------------------------------------------------------------

export const PRODUCT_OPERATIONS = ["CREATE", "EDIT", "ARCHIVE", "RESTORE", "APPROVE", "REJECT", "MERGE", "SPLIT"] as const;
export type ProductOperation = (typeof PRODUCT_OPERATIONS)[number];

export const PRODUCT_CHANGE_REQUEST_STATUSES = ["PENDING_APPROVAL", "APPROVED", "REJECTED", "APPLIED"] as const;
export type ProductChangeRequestStatus = (typeof PRODUCT_CHANGE_REQUEST_STATUSES)[number];

export interface ProductVersionEntry {
  version: number;
  at: string;
  actor: string;
  operation: ProductOperation;
  snapshot: Partial<ProductMaster>;
}

export interface ProductAuditEntry {
  id: string;
  operation: ProductOperation;
  actor: string;
  at: string;
  productIds: string[];
  before: Partial<ProductMaster>[];
  after: Partial<ProductMaster>[];
  note?: string;
}

export interface ProductChangeRequest {
  id: string;
  operation: ProductOperation;
  status: ProductChangeRequestStatus;
  requestedBy: string;
  reviewedBy: string | null;
  createdAt: string;
  updatedAt: string;
  payload: Record<string, unknown>;
  note?: string;
}

export type Clock = () => string;
