"use client";

import { useState } from "react";
import { OperationalBarChart } from "@/components/charts/operational-bar-chart";
import { MetricCard } from "@/components/dashboard/metric-card";
import { useSellerIntelligence } from "@/features/seller/queries";
import type { DemandForecast } from "@/features/merchant-intelligence";
import { EmptyState, IntelPageHeader, IntelSection, LoadingState, StatusPill } from "./primitives";

const pct = (value: number) => `${Math.round(value * 100)}%`;

function ForecastTable({ rows }: { rows: DemandForecast[] }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[680px] text-sm">
        <thead>
          <tr className="border-b text-left text-secondary-text">
            <th className="py-2 pr-3 font-medium">Product</th>
            <th className="py-2 pr-3 font-medium">Expected 7d</th>
            <th className="py-2 pr-3 font-medium">Daily run-rate</th>
            <th className="py-2 pr-3 font-medium">Days of cover</th>
            <th className="py-2 pr-3 font-medium">Stockout risk</th>
            <th className="py-2 pr-3 font-medium">Confidence</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((f) => (
            <tr key={f.productId} className="border-b border-border/40">
              <td className="py-2 pr-3 font-medium text-primary-text">{f.productName}</td>
              <td className="py-2 pr-3">{f.expectedUnits7d}</td>
              <td className="py-2 pr-3">{f.dailyRunRate.toFixed(1)}</td>
              <td className="py-2 pr-3">{f.daysOfCover ?? "—"}</td>
              <td className="py-2 pr-3"><StatusPill value={f.stockoutRisk} /></td>
              <td className="py-2 pr-3">{pct(f.confidence)}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function ForecastStudioScreen() {
  const { data: intel, isLoading } = useSellerIntelligence();
  if (isLoading) return <LoadingState />;
  if (!intel || intel.forecasts.length === 0) {
    return <EmptyState title="No demand forecasts yet" hint="Forecasts are generated from order history and run-rate signals. They appear once there is sales activity." />;
  }

  const top = [...intel.forecasts].sort((a, b) => b.expectedUnits7d - a.expectedUnits7d).slice(0, 12);
  const avgConfidence = intel.forecasts.reduce((sum, f) => sum + f.confidence, 0) / intel.forecasts.length;
  const highRisk = intel.forecasts.filter((f) => f.stockoutRisk === "high").length;

  return (
    <div className="space-y-6">
      <IntelPageHeader eyebrow="Forecast Studio" title="Demand forecasts" subtitle="7-day demand projections per product with stockout risk and confidence, generated by the merchant-intelligence engine." />
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <MetricCard label="Products forecast" value={String(intel.forecasts.length)} />
        <MetricCard label="Avg confidence (accuracy proxy)" value={pct(avgConfidence)} />
        <MetricCard label="High stockout risk" value={String(highRisk)} />
      </div>
      <IntelSection title="Expected units (top 12)" description="7-day expected demand by product.">
        <OperationalBarChart values={top.map((f) => f.expectedUnits7d)} />
      </IntelSection>
      <IntelSection title="Forecast detail" description={`${intel.forecasts.length} products. Confidence is the monitoring/accuracy proxy until actuals-vs-predicted tracking is wired.`}>
        <ForecastTable rows={intel.forecasts} />
      </IntelSection>
    </div>
  );
}

const scenarios = [
  { id: "soft", label: "Soft (-20%)", multiplier: 0.8 },
  { id: "baseline", label: "Baseline", multiplier: 1 },
  { id: "festival", label: "Festival (+30%)", multiplier: 1.3 },
  { id: "surge", label: "Surge (+60%)", multiplier: 1.6 },
];

export function ForecastScenariosScreen() {
  const { data: intel, isLoading } = useSellerIntelligence();
  const [scenarioId, setScenarioId] = useState("festival");
  if (isLoading) return <LoadingState />;
  if (!intel || intel.forecasts.length === 0) {
    return <EmptyState title="No forecasts to model" hint="Scenario forecasting needs baseline demand forecasts." />;
  }

  const scenario = scenarios.find((s) => s.id === scenarioId) ?? scenarios[1];
  const adjusted = intel.forecasts.map((f) => {
    const units = Math.round(f.expectedUnits7d * scenario.multiplier);
    const cover = f.daysOfCover === null ? null : Number((f.daysOfCover / scenario.multiplier).toFixed(1));
    const risk = cover === null ? f.stockoutRisk : cover < 3 ? "high" : cover < 7 ? "medium" : "low";
    return { ...f, expectedUnits7d: units, daysOfCover: cover, stockoutRisk: risk as DemandForecast["stockoutRisk"] };
  });
  const newHighRisk = adjusted.filter((f) => f.stockoutRisk === "high").length;

  return (
    <div className="space-y-6">
      <IntelPageHeader eyebrow="Forecast Studio" title="Scenario forecasting" subtitle="Apply a demand scenario multiplier to baseline forecasts and see the impact on volume and stockout risk." />
      <IntelSection title="Scenario" description="Choose a demand scenario to model.">
        <div className="flex flex-wrap gap-2">
          {scenarios.map((s) => (
            <button
              key={s.id}
              type="button"
              onClick={() => setScenarioId(s.id)}
              className={`rounded-md border px-3 py-1.5 text-sm font-medium ${s.id === scenarioId ? "border-primary bg-primary/10 text-primary" : "text-secondary-text"}`}
            >
              {s.label}
            </button>
          ))}
        </div>
        <p className="mt-3 text-sm text-secondary-text">Under <strong>{scenario.label}</strong>, {newHighRisk} products move to high stockout risk.</p>
      </IntelSection>
      <IntelSection title="Adjusted forecast">
        <ForecastTable rows={adjusted} />
      </IntelSection>
    </div>
  );
}

export function ForecastComparisonScreen() {
  const { data: intel, isLoading } = useSellerIntelligence();
  const [multiplier, setMultiplier] = useState(1.3);
  if (isLoading) return <LoadingState />;
  if (!intel || intel.forecasts.length === 0) {
    return <EmptyState title="No forecasts to compare" hint="Comparison needs baseline demand forecasts." />;
  }

  const rows = [...intel.forecasts]
    .sort((a, b) => b.expectedUnits7d - a.expectedUnits7d)
    .slice(0, 15)
    .map((f) => ({
      name: f.productName,
      baseline: f.expectedUnits7d,
      scenario: Math.round(f.expectedUnits7d * multiplier),
    }));
  const baselineTotal = rows.reduce((s, r) => s + r.baseline, 0);
  const scenarioTotal = rows.reduce((s, r) => s + r.scenario, 0);

  return (
    <div className="space-y-6">
      <IntelPageHeader eyebrow="Forecast Studio" title="Forecast comparison" subtitle="Compare baseline demand against a scenario multiplier across your top products." />
      <IntelSection title="Scenario multiplier" description={`Baseline total ${baselineTotal} → scenario total ${scenarioTotal} units (7d).`}>
        <input type="range" min={0.5} max={2} step={0.1} value={multiplier} onChange={(e) => setMultiplier(Number(e.target.value))} className="w-full max-w-md" />
        <p className="mt-2 text-sm text-secondary-text">Multiplier: <strong>{multiplier.toFixed(1)}×</strong></p>
      </IntelSection>
      <IntelSection title="Baseline vs scenario">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[480px] text-sm">
            <thead>
              <tr className="border-b text-left text-secondary-text">
                <th className="py-2 pr-3 font-medium">Product</th>
                <th className="py-2 pr-3 font-medium">Baseline 7d</th>
                <th className="py-2 pr-3 font-medium">Scenario 7d</th>
                <th className="py-2 pr-3 font-medium">Δ</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.name} className="border-b border-border/40">
                  <td className="py-2 pr-3 font-medium text-primary-text">{r.name}</td>
                  <td className="py-2 pr-3">{r.baseline}</td>
                  <td className="py-2 pr-3">{r.scenario}</td>
                  <td className={`py-2 pr-3 ${r.scenario - r.baseline >= 0 ? "text-emerald-600" : "text-red-600"}`}>{r.scenario - r.baseline >= 0 ? "+" : ""}{r.scenario - r.baseline}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </IntelSection>
    </div>
  );
}
