"use client";

import { MetricCard } from "@/components/dashboard/metric-card";
import { useSellerIntelligence } from "@/features/seller/queries";
import { EmptyState, IntelPageHeader, IntelSection, LoadingState } from "./primitives";

const pct = (value: number) => `${Math.round(value * 100)}%`;

export function SupplyIntelligenceScreen() {
  const { data: intel, isLoading } = useSellerIntelligence();
  if (isLoading) return <LoadingState />;
  if (!intel) {
    return <EmptyState title="No supply intelligence yet" hint="Hyperlocal demand and supply opportunity signals are generated from your catalog, orders, and service area." />;
  }

  const h = intel.hyperlocal;
  return (
    <div className="space-y-6">
      <IntelPageHeader eyebrow="Supply Intelligence" title="Hyperlocal demand & supply" subtitle="Local demand signals and category opportunities for your service area, generated by the hyperlocal intelligence engine." />
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        <MetricCard label="Locality" value={h.locality || "—"} />
        <MetricCard label="City" value={h.city || "—"} />
        <MetricCard label="Service radius" value={`${h.serviceRadiusKm} km`} />
      </div>
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <IntelSection title="Demand signals" description="Local demand indicators.">
          {h.demandSignals.length === 0 ? (
            <p className="text-sm text-secondary-text">No demand signals detected for this area yet.</p>
          ) : (
            <ul className="space-y-2">
              {h.demandSignals.map((signal, idx) => (
                <li key={idx} className="rounded-md border border-border/60 p-3 text-sm text-secondary-text">{signal}</li>
              ))}
            </ul>
          )}
        </IntelSection>
        <IntelSection title="Opportunity categories" description="Categories with supply/expansion opportunity.">
          {h.opportunityCategories.length === 0 ? (
            <p className="text-sm text-secondary-text">No category opportunities detected yet.</p>
          ) : (
            <ul className="space-y-2">
              {h.opportunityCategories.map((opp, idx) => (
                <li key={idx} className="flex items-start justify-between gap-3 rounded-md border border-border/60 p-3">
                  <span className="text-sm font-medium text-primary-text">{opp.category}</span>
                  <span className="text-xs text-secondary-text">{opp.signal}</span>
                </li>
              ))}
            </ul>
          )}
        </IntelSection>
      </div>
    </div>
  );
}

export function RoutingScreen() {
  const { data: intel, isLoading } = useSellerIntelligence();
  if (isLoading) return <LoadingState />;
  if (!intel) {
    return <EmptyState title="No fulfillment intelligence yet" hint="Routing and fulfillment signals are generated from active and delayed orders." />;
  }

  const f = intel.fulfillment;
  return (
    <div className="space-y-6">
      <IntelPageHeader eyebrow="Routing & Fulfillment" title="Fulfillment routing" subtitle="Fulfillment performance and bottlenecks. Route optimization across the delivery network is surfaced from order flow signals." />
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
        <MetricCard label="Active orders" value={String(f.activeOrders)} />
        <MetricCard label="Delayed" value={String(f.delayedOrders)} />
        <MetricCard label="Fulfillment rate" value={pct(f.fulfillmentRate)} />
        <MetricCard label="Cancellation rate" value={pct(f.cancellationRate)} />
        <MetricCard label="Avg promise (min)" value={String(Math.round(f.averagePromiseMinutes))} />
      </div>
      <IntelSection title="Bottlenecks" description="Where fulfillment is constrained.">
        {f.bottlenecks.length === 0 ? (
          <p className="text-sm text-secondary-text">No fulfillment bottlenecks detected.</p>
        ) : (
          <ul className="space-y-2">
            {f.bottlenecks.map((b, idx) => (
              <li key={idx} className="rounded-md border border-border/60 p-3 text-sm text-secondary-text">{b}</li>
            ))}
          </ul>
        )}
      </IntelSection>
    </div>
  );
}
