import { createHash } from "crypto";
import type { AsyncJobName, AsyncJobPriority, QueueDomain, QueuePolicy, WorkerPoolName, WorkerPoolPolicy } from "./types";

const commerceCritical = {
  domain: "commerce",
  workerPool: "commerce-critical",
  computeClass: "critical",
  maxAttempts: 8,
  baseRetryDelaySeconds: 30,
  maxRetryDelaySeconds: 900,
  concurrency: 8,
  minReservedConcurrency: 6,
  maxElasticConcurrency: 16,
  timeoutSeconds: 45,
  priority: 90,
  rateLimitPerMinute: 600,
  saturationBackoffSeconds: 15,
  deadLetterQueue: "commerce-critical.dlq",
  replayQueue: "commerce-critical.replay",
  allowBurst: true,
} as const;

export const queuePolicies = {
  "payment.webhook.reconcile": { ...commerceCritical, queueName: "commerce.checkout", category: "payment", partitionKey: "paymentId" },
  "payment.reconciliation.run": {
    ...commerceCritical,
    queueName: "commerce.reconciliation",
    category: "reconciliation",
    workerPool: "reconciliation-control",
    priority: 88,
    timeoutSeconds: 90,
    partitionKey: "provider",
  },
  "payment.refund.sync": { ...commerceCritical, queueName: "commerce.refunds", category: "payment", priority: 87, partitionKey: "refundId" },
  "payment.payout.verify": { ...commerceCritical, queueName: "commerce.payouts", category: "payment", priority: 84, partitionKey: "sellerId" },
  "india.upi.recover": { ...commerceCritical, queueName: "commerce.checkout", category: "payment", priority: 86, timeoutSeconds: 30, partitionKey: "paymentId" },

  "delivery.eta.refresh": {
    queueName: "logistics.eta",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "interactive",
    maxAttempts: 5,
    baseRetryDelaySeconds: 60,
    maxRetryDelaySeconds: 900,
    concurrency: 6,
    minReservedConcurrency: 3,
    maxElasticConcurrency: 10,
    timeoutSeconds: 30,
    priority: 65,
    rateLimitPerMinute: 420,
    saturationBackoffSeconds: 45,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "deliveryId",
  },
  "delivery.dispatch.recalculate": {
    queueName: "logistics.dispatch",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "interactive",
    maxAttempts: 6,
    baseRetryDelaySeconds: 45,
    maxRetryDelaySeconds: 900,
    concurrency: 6,
    minReservedConcurrency: 3,
    maxElasticConcurrency: 12,
    timeoutSeconds: 45,
    priority: 82,
    rateLimitPerMinute: 360,
    saturationBackoffSeconds: 45,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "zoneId",
  },
  "delivery.reconciliation.run": {
    queueName: "logistics.reconciliation",
    category: "delivery",
    domain: "logistics",
    workerPool: "reconciliation-control",
    computeClass: "standard",
    maxAttempts: 6,
    baseRetryDelaySeconds: 120,
    maxRetryDelaySeconds: 1800,
    concurrency: 3,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 6,
    timeoutSeconds: 90,
    priority: 76,
    rateLimitPerMinute: 120,
    saturationBackoffSeconds: 90,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "provider",
  },
  "delivery.failed.recover": {
    queueName: "logistics.tracking-replay",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "standard",
    maxAttempts: 6,
    baseRetryDelaySeconds: 180,
    maxRetryDelaySeconds: 3600,
    concurrency: 3,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 5,
    timeoutSeconds: 60,
    priority: 80,
    rateLimitPerMinute: 90,
    saturationBackoffSeconds: 120,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "deliveryId",
  },
  "delivery.provider.failover": {
    queueName: "logistics.provider-failover",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "critical",
    maxAttempts: 8,
    baseRetryDelaySeconds: 30,
    maxRetryDelaySeconds: 900,
    concurrency: 5,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 10,
    timeoutSeconds: 60,
    priority: 90,
    rateLimitPerMinute: 240,
    saturationBackoffSeconds: 30,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "provider",
    allowBurst: true,
  },
  "delivery.routing.refresh": {
    queueName: "logistics.routing",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "standard",
    maxAttempts: 4,
    baseRetryDelaySeconds: 120,
    maxRetryDelaySeconds: 1800,
    concurrency: 3,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 5,
    timeoutSeconds: 90,
    priority: 62,
    rateLimitPerMinute: 90,
    saturationBackoffSeconds: 120,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "zoneId",
  },
  "delivery.sla.recalculate": {
    queueName: "logistics.sla",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "standard",
    maxAttempts: 5,
    baseRetryDelaySeconds: 90,
    maxRetryDelaySeconds: 1200,
    concurrency: 4,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 7,
    timeoutSeconds: 60,
    priority: 74,
    rateLimitPerMinute: 180,
    saturationBackoffSeconds: 90,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "zoneId",
  },
  "delivery.congestion.analyze": {
    queueName: "logistics.congestion",
    category: "delivery",
    domain: "logistics",
    workerPool: "logistics-coordination",
    computeClass: "standard",
    maxAttempts: 4,
    baseRetryDelaySeconds: 180,
    maxRetryDelaySeconds: 1800,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 90,
    priority: 58,
    rateLimitPerMinute: 90,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "logistics.dlq",
    replayQueue: "logistics.replay",
    partitionKey: "zoneId",
  },

  "ai.embedding.refresh": {
    queueName: "ai.embeddings",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "heavy",
    maxAttempts: 4,
    baseRetryDelaySeconds: 180,
    maxRetryDelaySeconds: 3600,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 90,
    priority: 45,
    rateLimitPerMinute: 90,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "productId",
  },
  "ai.embedding.refresh_stale": {
    queueName: "ai.embeddings-scheduled",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "bulk",
    maxAttempts: 4,
    baseRetryDelaySeconds: 300,
    maxRetryDelaySeconds: 7200,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 3,
    timeoutSeconds: 180,
    priority: 35,
    rateLimitPerMinute: 30,
    saturationBackoffSeconds: 300,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
  },
  "ai.semantic.index": {
    queueName: "ai.semantic-index",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "heavy",
    maxAttempts: 4,
    baseRetryDelaySeconds: 240,
    maxRetryDelaySeconds: 7200,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 3,
    timeoutSeconds: 180,
    priority: 42,
    rateLimitPerMinute: 45,
    saturationBackoffSeconds: 240,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "catalogShard",
  },
  "ai.recommendations.recalculate": {
    queueName: "ai.recommendations",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 600,
    maxRetryDelaySeconds: 7200,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 2,
    timeoutSeconds: 180,
    priority: 30,
    rateLimitPerMinute: 20,
    saturationBackoffSeconds: 420,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "sellerId",
  },
  "ai.ranking.recalculate": {
    queueName: "ai.ranking",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 600,
    maxRetryDelaySeconds: 7200,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 2,
    timeoutSeconds: 180,
    priority: 32,
    rateLimitPerMinute: 20,
    saturationBackoffSeconds: 420,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "marketId",
  },
  "ai.diagnostics.run": {
    queueName: "ai.diagnostics",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "standard",
    maxAttempts: 3,
    baseRetryDelaySeconds: 300,
    maxRetryDelaySeconds: 3600,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 2,
    timeoutSeconds: 120,
    priority: 38,
    rateLimitPerMinute: 30,
    saturationBackoffSeconds: 240,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
  },
  "ai.feedback.aggregate": {
    queueName: "ai.feedback",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "standard",
    maxAttempts: 4,
    baseRetryDelaySeconds: 180,
    maxRetryDelaySeconds: 3600,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 90,
    priority: 44,
    rateLimitPerMinute: 120,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "marketId",
  },
  "ai.personalization.refresh": {
    queueName: "ai.personalization",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "interactive",
    maxAttempts: 3,
    baseRetryDelaySeconds: 120,
    maxRetryDelaySeconds: 1800,
    concurrency: 3,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 5,
    timeoutSeconds: 45,
    priority: 50,
    rateLimitPerMinute: 240,
    saturationBackoffSeconds: 90,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "profileFingerprint",
  },
  "ai.retrieval.observe": {
    queueName: "ai.observability",
    category: "ai",
    domain: "ai",
    workerPool: "ai-heavy-compute",
    computeClass: "standard",
    maxAttempts: 3,
    baseRetryDelaySeconds: 180,
    maxRetryDelaySeconds: 3600,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 60,
    priority: 48,
    rateLimitPerMinute: 180,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "ai.dlq",
    replayQueue: "ai.replay",
    partitionKey: "retrievalMode",
  },

  "governance.fraud.scan": {
    queueName: "governance.fraud",
    category: "governance",
    domain: "governance",
    workerPool: "governance-risk",
    computeClass: "standard",
    maxAttempts: 5,
    baseRetryDelaySeconds: 180,
    maxRetryDelaySeconds: 3600,
    concurrency: 3,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 6,
    timeoutSeconds: 90,
    priority: 70,
    rateLimitPerMinute: 120,
    saturationBackoffSeconds: 120,
    deadLetterQueue: "governance.dlq",
    replayQueue: "governance.replay",
    partitionKey: "sellerId",
  },
  "governance.moderation.scan": {
    queueName: "governance.moderation",
    category: "governance",
    domain: "governance",
    workerPool: "governance-risk",
    computeClass: "standard",
    maxAttempts: 4,
    baseRetryDelaySeconds: 240,
    maxRetryDelaySeconds: 3600,
    concurrency: 3,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 5,
    timeoutSeconds: 90,
    priority: 55,
    rateLimitPerMinute: 90,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "governance.dlq",
    replayQueue: "governance.replay",
    partitionKey: "moderationShard",
  },
  "governance.trust.recalculate": {
    queueName: "governance.trust",
    category: "governance",
    domain: "governance",
    workerPool: "governance-risk",
    computeClass: "standard",
    maxAttempts: 4,
    baseRetryDelaySeconds: 240,
    maxRetryDelaySeconds: 3600,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 90,
    priority: 62,
    rateLimitPerMinute: 80,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "governance.dlq",
    replayQueue: "governance.replay",
    partitionKey: "sellerId",
  },
  "governance.dispute.analyze": {
    queueName: "governance.disputes",
    category: "governance",
    domain: "governance",
    workerPool: "governance-risk",
    computeClass: "standard",
    maxAttempts: 4,
    baseRetryDelaySeconds: 240,
    maxRetryDelaySeconds: 3600,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 120,
    priority: 68,
    rateLimitPerMinute: 60,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "governance.dlq",
    replayQueue: "governance.replay",
    partitionKey: "disputeId",
  },

  "localization.audit": {
    queueName: "analytics.operational",
    category: "analytics",
    domain: "analytics",
    workerPool: "analytics-bulk",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 600,
    maxRetryDelaySeconds: 7200,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 2,
    timeoutSeconds: 60,
    priority: 35,
    rateLimitPerMinute: 30,
    saturationBackoffSeconds: 420,
    deadLetterQueue: "analytics.dlq",
    replayQueue: "analytics.replay",
  },
  "analytics.seller.aggregate": {
    queueName: "analytics.seller-aggregation",
    category: "analytics",
    domain: "analytics",
    workerPool: "analytics-bulk",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 600,
    maxRetryDelaySeconds: 7200,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 180,
    priority: 25,
    rateLimitPerMinute: 60,
    saturationBackoffSeconds: 420,
    deadLetterQueue: "analytics.dlq",
    replayQueue: "analytics.replay",
    partitionKey: "sellerId",
  },
  "analytics.forecast.run": {
    queueName: "analytics.forecasting",
    category: "analytics",
    domain: "analytics",
    workerPool: "analytics-bulk",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 900,
    maxRetryDelaySeconds: 7200,
    concurrency: 1,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 2,
    timeoutSeconds: 240,
    priority: 22,
    rateLimitPerMinute: 20,
    saturationBackoffSeconds: 600,
    deadLetterQueue: "analytics.dlq",
    replayQueue: "analytics.replay",
    partitionKey: "marketId",
  },
  "analytics.operational.metrics": {
    queueName: "analytics.operational",
    category: "analytics",
    domain: "analytics",
    workerPool: "analytics-bulk",
    computeClass: "standard",
    maxAttempts: 3,
    baseRetryDelaySeconds: 300,
    maxRetryDelaySeconds: 3600,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 90,
    priority: 40,
    rateLimitPerMinute: 120,
    saturationBackoffSeconds: 180,
    deadLetterQueue: "analytics.dlq",
    replayQueue: "analytics.replay",
  },
  "analytics.admin.refresh": {
    queueName: "analytics.admin",
    category: "analytics",
    domain: "analytics",
    workerPool: "analytics-bulk",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 600,
    maxRetryDelaySeconds: 7200,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 3,
    timeoutSeconds: 180,
    priority: 25,
    rateLimitPerMinute: 60,
    saturationBackoffSeconds: 420,
    deadLetterQueue: "analytics.dlq",
    replayQueue: "analytics.replay",
  },

  "notification.dispatch": {
    queueName: "notifications.dispatch",
    category: "notification",
    domain: "notification",
    workerPool: "notification-delivery",
    computeClass: "interactive",
    maxAttempts: 6,
    baseRetryDelaySeconds: 60,
    maxRetryDelaySeconds: 1800,
    concurrency: 10,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 18,
    timeoutSeconds: 30,
    priority: 50,
    rateLimitPerMinute: 900,
    saturationBackoffSeconds: 60,
    deadLetterQueue: "notifications.dlq",
    replayQueue: "notifications.replay",
    partitionKey: "recipientId",
    allowBurst: true,
  },
  "notification.email.deliver": {
    queueName: "notifications.email",
    category: "notification",
    domain: "notification",
    workerPool: "notification-delivery",
    computeClass: "interactive",
    maxAttempts: 6,
    baseRetryDelaySeconds: 90,
    maxRetryDelaySeconds: 1800,
    concurrency: 8,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 14,
    timeoutSeconds: 30,
    priority: 52,
    rateLimitPerMinute: 600,
    saturationBackoffSeconds: 60,
    deadLetterQueue: "notifications.dlq",
    replayQueue: "notifications.replay",
    partitionKey: "recipientId",
  },
  "notification.push.deliver": {
    queueName: "notifications.push",
    category: "notification",
    domain: "notification",
    workerPool: "notification-delivery",
    computeClass: "interactive",
    maxAttempts: 6,
    baseRetryDelaySeconds: 60,
    maxRetryDelaySeconds: 1200,
    concurrency: 10,
    minReservedConcurrency: 2,
    maxElasticConcurrency: 18,
    timeoutSeconds: 20,
    priority: 54,
    rateLimitPerMinute: 1200,
    saturationBackoffSeconds: 45,
    deadLetterQueue: "notifications.dlq",
    replayQueue: "notifications.replay",
    partitionKey: "recipientId",
    allowBurst: true,
  },
  "notification.sms.placeholder": {
    queueName: "notifications.sms",
    category: "notification",
    domain: "notification",
    workerPool: "notification-delivery",
    computeClass: "interactive",
    maxAttempts: 4,
    baseRetryDelaySeconds: 120,
    maxRetryDelaySeconds: 1800,
    concurrency: 4,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 8,
    timeoutSeconds: 30,
    priority: 48,
    rateLimitPerMinute: 240,
    saturationBackoffSeconds: 90,
    deadLetterQueue: "notifications.dlq",
    replayQueue: "notifications.replay",
    partitionKey: "recipientId",
  },
  "notification.digest.batch": {
    queueName: "notifications.digest",
    category: "notification",
    domain: "notification",
    workerPool: "notification-delivery",
    computeClass: "bulk",
    maxAttempts: 3,
    baseRetryDelaySeconds: 600,
    maxRetryDelaySeconds: 7200,
    concurrency: 2,
    minReservedConcurrency: 1,
    maxElasticConcurrency: 4,
    timeoutSeconds: 90,
    priority: 25,
    rateLimitPerMinute: 60,
    saturationBackoffSeconds: 420,
    deadLetterQueue: "notifications.dlq",
    replayQueue: "notifications.replay",
  },

  "realtime.invalidation.flush": {
    queueName: "realtime.invalidation",
    category: "realtime",
    domain: "realtime",
    workerPool: "realtime-sync",
    computeClass: "interactive",
    maxAttempts: 4,
    baseRetryDelaySeconds: 20,
    maxRetryDelaySeconds: 300,
    concurrency: 8,
    minReservedConcurrency: 3,
    maxElasticConcurrency: 14,
    timeoutSeconds: 20,
    priority: 60,
    rateLimitPerMinute: 900,
    saturationBackoffSeconds: 20,
    deadLetterQueue: "realtime.dlq",
    replayQueue: "realtime.replay",
    partitionKey: "channel",
    allowBurst: true,
  },
} as const satisfies Record<AsyncJobName, QueuePolicy>;

export const workerPoolPolicies = {
  "commerce-critical": {
    name: "commerce-critical",
    queues: ["commerce.checkout", "commerce.refunds", "commerce.payouts"],
    minWorkers: 2,
    maxWorkers: 8,
    maxJobsPerRun: 24,
    heartbeatTtlSeconds: 90,
    gracefulShutdownSeconds: 30,
    scaleUpBacklogPerWorker: 50,
    scaleDownIdleRuns: 3,
    reservedForDomains: ["commerce"],
  },
  "reconciliation-control": {
    name: "reconciliation-control",
    queues: ["commerce.reconciliation", "logistics.reconciliation"],
    minWorkers: 1,
    maxWorkers: 4,
    maxJobsPerRun: 12,
    heartbeatTtlSeconds: 120,
    gracefulShutdownSeconds: 45,
    scaleUpBacklogPerWorker: 35,
    scaleDownIdleRuns: 4,
    reservedForDomains: ["commerce", "logistics"],
  },
  "logistics-coordination": {
    name: "logistics-coordination",
    queues: ["logistics.eta", "logistics.dispatch", "logistics.tracking-replay", "logistics.provider-failover", "logistics.routing", "logistics.sla", "logistics.congestion"],
    minWorkers: 1,
    maxWorkers: 5,
    maxJobsPerRun: 18,
    heartbeatTtlSeconds: 120,
    gracefulShutdownSeconds: 45,
    scaleUpBacklogPerWorker: 45,
    scaleDownIdleRuns: 4,
    reservedForDomains: ["logistics"],
  },
  "ai-heavy-compute": {
    name: "ai-heavy-compute",
    queues: ["ai.embeddings", "ai.embeddings-scheduled", "ai.semantic-index", "ai.recommendations", "ai.ranking", "ai.diagnostics", "ai.feedback", "ai.personalization", "ai.observability"],
    minWorkers: 1,
    maxWorkers: 4,
    maxJobsPerRun: 8,
    heartbeatTtlSeconds: 180,
    gracefulShutdownSeconds: 90,
    scaleUpBacklogPerWorker: 120,
    scaleDownIdleRuns: 6,
    reservedForDomains: ["ai"],
  },
  "governance-risk": {
    name: "governance-risk",
    queues: ["governance.fraud", "governance.moderation", "governance.trust", "governance.disputes"],
    minWorkers: 1,
    maxWorkers: 5,
    maxJobsPerRun: 14,
    heartbeatTtlSeconds: 150,
    gracefulShutdownSeconds: 60,
    scaleUpBacklogPerWorker: 50,
    scaleDownIdleRuns: 4,
    reservedForDomains: ["governance"],
  },
  "analytics-bulk": {
    name: "analytics-bulk",
    queues: ["analytics.seller-aggregation", "analytics.forecasting", "analytics.operational", "analytics.admin"],
    minWorkers: 1,
    maxWorkers: 3,
    maxJobsPerRun: 10,
    heartbeatTtlSeconds: 180,
    gracefulShutdownSeconds: 90,
    scaleUpBacklogPerWorker: 140,
    scaleDownIdleRuns: 6,
    reservedForDomains: ["analytics"],
  },
  "notification-delivery": {
    name: "notification-delivery",
    queues: ["notifications.dispatch", "notifications.email", "notifications.push", "notifications.sms", "notifications.digest"],
    minWorkers: 1,
    maxWorkers: 7,
    maxJobsPerRun: 28,
    heartbeatTtlSeconds: 90,
    gracefulShutdownSeconds: 30,
    scaleUpBacklogPerWorker: 100,
    scaleDownIdleRuns: 3,
    reservedForDomains: ["notification"],
  },
  "realtime-sync": {
    name: "realtime-sync",
    queues: ["realtime.invalidation"],
    minWorkers: 1,
    maxWorkers: 4,
    maxJobsPerRun: 18,
    heartbeatTtlSeconds: 60,
    gracefulShutdownSeconds: 20,
    scaleUpBacklogPerWorker: 60,
    scaleDownIdleRuns: 3,
    reservedForDomains: ["realtime"],
  },
} as const satisfies Record<WorkerPoolName, WorkerPoolPolicy>;

export const queueAliases: Record<string, string[]> = {
  "commerce-critical": ["commerce.checkout", "commerce.reconciliation", "commerce.refunds", "commerce.payouts"],
  delivery: ["logistics.eta", "logistics.dispatch", "logistics.reconciliation", "logistics.tracking-replay", "logistics.provider-failover", "logistics.routing", "logistics.sla", "logistics.congestion"],
  "ai-maintenance": ["ai.embeddings", "ai.embeddings-scheduled", "ai.semantic-index", "ai.recommendations", "ai.ranking", "ai.diagnostics", "ai.feedback", "ai.personalization", "ai.observability"],
  governance: ["governance.fraud", "governance.moderation", "governance.trust", "governance.disputes"],
  notifications: ["notifications.dispatch", "notifications.email", "notifications.push", "notifications.sms", "notifications.digest"],
  analytics: ["analytics.seller-aggregation", "analytics.forecasting", "analytics.operational", "analytics.admin"],
  realtime: ["realtime.invalidation"],
};

export function policyForJob(name: AsyncJobName): QueuePolicy {
  return queuePolicies[name];
}

export function priorityValue(priority: AsyncJobPriority | undefined, policy: QueuePolicy) {
  if (typeof priority === "number") return Math.max(0, Math.min(100, priority));
  if (priority === "critical") return 95;
  if (priority === "high") return 80;
  if (priority === "low") return 20;
  return policy.priority;
}

export function retryDelayForAttempt(policy: QueuePolicy, attempt: number, pressure = 0) {
  const jitterWindow = Math.max(5, Math.floor(policy.baseRetryDelaySeconds / 2));
  const jitterSeed = createHash("sha256").update(`${policy.queueName}:${policy.category}:${attempt}`).digest("hex").slice(0, 8);
  const jitter = Number.parseInt(jitterSeed, 16) % jitterWindow;
  const exponential = policy.baseRetryDelaySeconds * 2 ** Math.max(0, attempt - 1);
  const pressureBackoff = Math.ceil(Math.max(0, pressure) * policy.saturationBackoffSeconds);
  return Math.min(policy.maxRetryDelaySeconds, exponential + jitter + pressureBackoff);
}

export function expandQueueNames(queueNames: string[]) {
  return [...new Set(queueNames.flatMap((queueName) => queueAliases[queueName] ?? [queueName]))];
}

export function queueNamesForDomain(domain: QueueDomain) {
  return [...new Set(Object.values(queuePolicies).filter((policy) => policy.domain === domain).map((policy) => policy.queueName))];
}

export function queueNamesForPool(poolName: WorkerPoolName) {
  return workerPoolPolicies[poolName].queues;
}

export function allDistributedQueueNames() {
  return [...new Set(Object.values(queuePolicies).map((policy) => policy.queueName))];
}

export function workerPoolForName(poolName: WorkerPoolName) {
  return workerPoolPolicies[poolName];
}

export function concurrencyLimitsForQueues(queueNames: string[], pressureByQueue: Record<string, number> = {}) {
  const expanded = expandQueueNames(queueNames);
  const limits = Object.values(queuePolicies).reduce<Record<string, number>>((current, policy) => {
    const pressure = pressureByQueue[policy.queueName] ?? 0;
    const elastic = pressure > 0.75 ? policy.maxElasticConcurrency : policy.concurrency;
    current[policy.queueName] = Math.max(current[policy.queueName] ?? 0, Math.max(policy.minReservedConcurrency, elastic));
    return current;
  }, {});

  return Object.fromEntries(expanded.map((queueName) => [queueName, limits[queueName] ?? 1]));
}

export function lockSecondsForQueues(queueNames: string[]) {
  const expanded = expandQueueNames(queueNames);
  return Math.max(
    30,
    ...Object.values(queuePolicies)
      .filter((policy) => expanded.includes(policy.queueName))
      .map((policy) => policy.timeoutSeconds + 30),
  );
}
