import {
  Activity,
  BarChart3,
  Boxes,
  Brain,
  ClipboardCheck,
  ClipboardList,
  Bell,
  CircleHelp,
  FileUp,
  Heart,
  Home,
  Images,
  LayoutDashboard,
  ListChecks,
  MapPin,
  PackageSearch,
  ReceiptText,
  Rocket,
  Search,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  Store,
  Tags,
  Truck,
  User,
  Users,
  WalletCards,
  BellRing,
  FileClock,
  Flag,
  HeartPulse,
  PackageCheck,
  Compass,
  Gift,
  TrendingUp,
} from "lucide-react";

export const buyerNavigation = [
  { label: "Home", href: "/", icon: Home },
  { label: "Search", href: "/search", icon: Search },
  { label: "Discover", href: "/discover", icon: Compass },
  { label: "Nearby", href: "/nearby", icon: MapPin },
  { label: "Categories", href: "/categories", icon: Tags },
  { label: "Orders", href: "/orders", icon: ReceiptText },
  { label: "Rewards", href: "/rewards", icon: Gift },
  { label: "Wishlist", href: "/wishlist", icon: Heart },
  { label: "Profile", href: "/profile", icon: User },
] as const;

export const sellerNavigation = [
  { label: "Dashboard", href: "/seller/dashboard", icon: LayoutDashboard },
  { label: "Activation", href: "/seller/activation", icon: Rocket },
  { label: "Onboarding", href: "/seller/onboarding", icon: ClipboardCheck },
  { label: "Operations", href: "/seller/operations", icon: Activity },
  { label: "Fulfillment", href: "/seller/fulfillment", icon: PackageCheck },
  { label: "Hyperlocal", href: "/seller/hyperlocal", icon: MapPin },
  { label: "Intelligence", href: "/seller/intelligence", icon: Brain },
  { label: "Reputation", href: "/seller/reputation", icon: ShieldCheck },
  { label: "Products", href: "/seller/products", icon: PackageSearch },
  { label: "Import", href: "/seller/import", icon: FileUp },
  { label: "Catalog Ops", href: "/seller/catalog-ops", icon: ListChecks },
  { label: "Catalog", href: "/seller/catalog", icon: ListChecks },
  { label: "Media", href: "/seller/media", icon: Images },
  { label: "Inventory", href: "/seller/inventory", icon: Boxes },
  { label: "Orders", href: "/seller/orders", icon: ClipboardList },
  { label: "Analytics", href: "/seller/analytics", icon: BarChart3 },
  { label: "Store settings", href: "/seller/store-settings", icon: Settings2 },
  { label: "Notifications", href: "/seller/notifications", icon: Bell },
  { label: "Payouts", href: "/seller/payouts", icon: WalletCards },
  { label: "Support", href: "/seller/support", icon: CircleHelp },
] as const;

export const adminNavigation = [
  { label: "Dashboard", href: "/admin/dashboard", icon: LayoutDashboard },
  { label: "Platform", href: "/platform", icon: Compass },
  { label: "Intelligence", href: "/admin/intelligence", icon: Brain },
  { label: "Execution", href: "/admin/execution", icon: Rocket },
  { label: "Vendors", href: "/admin/vendors", icon: Users },
  { label: "Sellers", href: "/admin/sellers", icon: Store },
  { label: "Population", href: "/admin/population", icon: BarChart3 },
  { label: "Moderation", href: "/admin/moderation", icon: ShieldCheck },
  { label: "Catalog", href: "/admin/catalog", icon: Boxes },
  { label: "Catalog gov", href: "/admin/catalog-governance", icon: ListChecks },
  { label: "Media", href: "/admin/media", icon: Images },
  { label: "Trust", href: "/admin/trust", icon: ShieldCheck },
  { label: "Orders", href: "/admin/orders", icon: PackageCheck },
  { label: "Commerce", href: "/admin/commerce", icon: ShoppingCart },
  { label: "Location", href: "/admin/location", icon: MapPin },
  { label: "Growth", href: "/admin/growth", icon: TrendingUp },
  { label: "Refunds", href: "/admin/refunds", icon: WalletCards },
  { label: "Categories", href: "/admin/categories", icon: ListChecks },
  { label: "Analytics", href: "/admin/analytics", icon: BarChart3 },
  { label: "Notifications", href: "/admin/notifications", icon: BellRing },
  { label: "Flags", href: "/admin/flags", icon: Flag },
  { label: "Audit logs", href: "/admin/audit-logs", icon: FileClock },
  { label: "Platform health", href: "/admin/platform-health", icon: HeartPulse },
  { label: "Settings", href: "/admin/settings", icon: Settings2 },
] as const;

export const buyerQuickActions = [
  { label: "Cart", href: "/cart", icon: ShoppingCart },
  { label: "Tracking", href: "/tracking", icon: Truck },
] as const;
