// KARTEX Phase N — Subsystems (M1–M8) and the canonical intelligence flow.

import type { FlowStage, Subsystem } from "./types";

export const subsystems: Subsystem[] = [
  {
    id: "research",
    phase: "M1",
    name: "Research OS",
    icon: "Microscope",
    accent: "research",
    tagline: "Turns raw signals into structured, sourced research.",
    what: "A research operating system that gathers, structures and synthesises evidence from internal and external signals.",
    why: "Decisions made without evidence are guesses. Research OS makes evidence a first-class, reusable asset.",
    problem: "Teams drown in disconnected data and anecdotes; insight is slow, unsourced and easily lost.",
    value: "Faster, traceable insight generation with explicit sources and confidence.",
    beneficiaries: ["Analysts", "Strategy teams", "Product managers"],
    capabilities: ["Signal ingestion", "Evidence synthesis", "Source traceability", "Hypothesis seeding"],
    route: null,
    dependsOn: [],
    layerKind: "flow",
    flowOrder: 1,
  },
  {
    id: "knowledge",
    phase: "M2",
    name: "Knowledge OS",
    icon: "BrainCircuit",
    accent: "knowledge",
    tagline: "Converts research into durable, reusable knowledge.",
    what: "A knowledge operating system that organises validated findings into a connected, versioned knowledge graph.",
    why: "Knowledge that cannot be reused decays. Knowledge OS keeps understanding current and connected.",
    problem: "Insights are rediscovered repeatedly; taxonomy drifts and institutional memory erodes.",
    value: "Compounding knowledge reuse and drift detection across the organisation.",
    beneficiaries: ["Knowledge managers", "Analysts", "New team members"],
    capabilities: ["Knowledge graph", "Belief revision", "Drift detection", "Concept lineage"],
    route: null,
    dependsOn: ["research"],
    layerKind: "flow",
    flowOrder: 2,
  },
  {
    id: "simulation",
    phase: "M3",
    name: "Simulation OS",
    icon: "Workflow",
    accent: "simulation",
    tagline: "Tests decisions before they touch the real world.",
    what: "A simulation operating system that models scenarios and forecasts outcomes from current knowledge.",
    why: "Acting first and learning later is expensive. Simulation lets you fail safely, on paper.",
    problem: "Strategic choices are made without understanding second-order effects or downside risk.",
    value: "De-risked decisions through scenario modelling and outcome forecasting.",
    beneficiaries: ["Operations leaders", "Planners", "Executives"],
    capabilities: ["Scenario modelling", "Outcome forecasting", "What-if analysis", "Sensitivity testing"],
    route: null,
    dependsOn: ["knowledge"],
    layerKind: "flow",
    flowOrder: 3,
  },
  {
    id: "secis",
    phase: "M4",
    name: "SECIS",
    icon: "ShieldCheck",
    accent: "secis",
    tagline: "Epistemic security: defends the integrity of intelligence.",
    what: "A security and epistemic-integrity system that detects corruption, poisoning and manipulation of knowledge and signals.",
    why: "Intelligence is only useful if it can be trusted. SECIS protects the truth the platform relies on.",
    problem: "Bad data, manipulation and drift can silently corrupt every downstream decision.",
    value: "Trustworthy intelligence with detected threats, calibrated confidence and integrity guarantees.",
    beneficiaries: ["Risk officers", "Security teams", "Decision makers"],
    capabilities: ["Threat detection", "Data-poisoning defence", "Calibration", "Integrity scoring"],
    route: null,
    dependsOn: ["knowledge", "simulation"],
    layerKind: "flow",
    flowOrder: 4,
  },
  {
    id: "governance",
    phase: "M5",
    name: "Governance OS",
    icon: "Scale",
    accent: "governance",
    tagline: "Turns validated intelligence into approved decisions.",
    what: "A governance operating system that reviews, approves and records decisions with full accountability.",
    why: "Insight without a decision is inert. Governance converts analysis into authorised, auditable choices.",
    problem: "Decisions are made informally, without approval trails, ownership or accountability.",
    value: "Accountable, auditable decisions ready to be executed.",
    beneficiaries: ["Executives", "Governance boards", "Compliance"],
    capabilities: ["Decision review", "Approval workflow", "Risk signals", "Audit trail"],
    route: "/admin/dashboard",
    dependsOn: ["secis", "simulation", "knowledge"],
    layerKind: "flow",
    flowOrder: 5,
  },
  {
    id: "execution",
    phase: "M8",
    name: "Execution OS",
    icon: "Rocket",
    accent: "execution",
    tagline: "Converts decisions into owned, measurable work.",
    what: "An execution operating system that turns approved decisions into programs, initiatives, action plans and tracked outcomes.",
    why: "A decision that is never executed and measured creates no value. Execution closes the loop.",
    problem: "Approved decisions stall; nothing is owned, tracked, measured or closed.",
    value: "Decisions become measurable outcomes through owned, audited execution.",
    beneficiaries: ["Operators", "Program managers", "Owners"],
    capabilities: ["Action plans", "Initiatives & programs", "KPI tracking", "Outcome measurement", "Decision activation"],
    route: "/admin/execution",
    dependsOn: ["governance"],
    layerKind: "flow",
    flowOrder: 6,
  },
  {
    id: "integration",
    phase: "M6",
    name: "Integration Layer",
    icon: "Network",
    accent: "integration",
    tagline: "The connective fabric between every subsystem.",
    what: "An integration layer providing shared contracts, APIs and data flow that bind the subsystems into one platform.",
    why: "Subsystems in isolation are tools; integrated, they are a platform. This layer makes the whole greater than its parts.",
    problem: "Disconnected tools force manual hand-offs, re-entry and brittle glue code.",
    value: "Seamless, contract-driven flow of intelligence with no manual re-entry between stages.",
    beneficiaries: ["Engineers", "Platform teams", "Every subsystem"],
    capabilities: ["Shared API contracts", "Typed envelopes", "Event flow", "Cross-system wiring"],
    route: null,
    dependsOn: ["research", "knowledge", "simulation", "secis", "governance"],
    layerKind: "fabric",
    flowOrder: null,
  },
  {
    id: "workspace",
    phase: "M7",
    name: "Workspace Layer",
    icon: "LayoutDashboard",
    accent: "workspace",
    tagline: "The human surface where the platform is operated.",
    what: "A workspace layer of dashboards and operator surfaces where people review, navigate and act on the platform.",
    why: "Intelligence must reach humans to matter. The workspace makes the platform usable, not just powerful.",
    problem: "Powerful back-ends are useless if operators cannot see, understand or act on them.",
    value: "An accessible, role-aware surface that makes the entire platform operable by people.",
    beneficiaries: ["Operators", "Admins", "Every user"],
    capabilities: ["Dashboards", "Navigation", "Role-aware views", "Operator workflows"],
    route: "/admin/dashboard",
    dependsOn: ["integration"],
    layerKind: "fabric",
    flowOrder: null,
  },
];

/** The canonical intelligence flow: Research → Knowledge → Simulation → SECIS → Governance → Execution. */
export const intelligenceFlow: FlowStage[] = subsystems
  .filter((subsystem) => subsystem.layerKind === "flow")
  .sort((a, b) => (a.flowOrder ?? 0) - (b.flowOrder ?? 0))
  .map((subsystem) => ({
    order: subsystem.flowOrder as number,
    subsystemId: subsystem.id,
    title: subsystem.name,
    description: subsystem.tagline,
  }));

export const FLOW_SUBSYSTEM_IDS = intelligenceFlow.map((stage) => stage.subsystemId);
