import type { CommerceRegion } from "@/types/commerce-foundation";
import { slugify } from "./slug";
import type { TaxonomyNodeInput } from "./types";

/**
 * Canonical, production-grade sample taxonomy for VendorHub (PP-1).
 *
 * This is reference/ontology data — NOT products, inventory, sellers or stores. It defines the
 * Department > Category > Subcategory > Product Family > Product Type > Variant Group hierarchy that
 * the marketplace classifies against. The {@link buildCanonicalTaxonomyInputs} builder expands it
 * into engine inputs with deterministic, globally-unique hierarchical slugs.
 */

type TypeSeed = string | { name: string; variantGroups?: string[] };
type FamilySeed = { name: string; attributeKeys?: string[]; types?: TypeSeed[] };
type SubcategorySeed = string | { name: string; families?: FamilySeed[] };
type CategorySeed = string | { name: string; attributeKeys?: string[]; subcategories?: SubcategorySeed[] };

interface DepartmentSeed {
  name: string;
  regions?: CommerceRegion[];
  attributeKeys?: string[];
  categories: CategorySeed[];
}

const ALL_SOUTH: CommerceRegion[] = ["TN", "KL", "KA", "AP", "TS"];

export const CANONICAL_DEPARTMENTS: DepartmentSeed[] = [
  {
    name: "Groceries",
    categories: [
      "Rice",
      "Wheat & Atta",
      "Pulses & Dals",
      "Edible Oils",
      "Sugar & Jaggery",
      "Salt",
      { name: "Spices & Masalas", attributeKeys: ["organic"], subcategories: ["Whole Spices", "Ground Spices", "Blended Masalas", "Pickle Masalas"] },
      "Dry Fruits & Nuts",
      "Flours & Sooji",
      "Rava & Vermicelli",
      "Poha & Beaten Rice",
      "Sabudana & Sago",
      "Cereals & Millets",
      "Ready Mixes",
      "Pickles & Chutneys",
      "Papads & Vadams",
      "Honey & Spreads",
      "Vinegar & Cooking Wines",
      "Canned & Tinned Foods",
      "Pasta & Noodles",
      "Sauces & Ketchups",
      "Baking Essentials",
      "Instant Food Mixes",
      "Cooking Pastes",
      "Dates & Figs",
    ],
  },
  {
    name: "Fresh Produce",
    attributeKeys: ["organic", "storage_type"],
    categories: [
      { name: "Fresh Vegetables", subcategories: ["Daily Vegetables", "Gourds & Pumpkins", "Beans & Peas", "Brinjal & Okra"] },
      "Leafy Greens",
      "Root Vegetables",
      "Exotic Vegetables",
      "Fresh Fruits",
      "Seasonal Fruits",
      "Exotic Fruits",
      "Citrus Fruits",
      "Berries",
      "Fresh Herbs",
      "Sprouts",
      "Organic Vegetables",
      "Organic Fruits",
      "Cut & Peeled Produce",
      "Coconuts",
      "Bananas",
      "Mangoes",
      "Tomatoes & Onions",
      "Potatoes",
      "Ginger & Garlic",
      "Green Chillies",
      "Flowers for Cooking",
    ],
  },
  {
    name: "Dairy",
    attributeKeys: ["storage_type", "vegetarian"],
    categories: [
      {
        name: "Milk",
        subcategories: [
          {
            name: "Liquid Milk",
            families: [
              {
                name: "Cow & Buffalo Milk",
                attributeKeys: ["volume", "organic"],
                types: [
                  { name: "Full Cream Milk", variantGroups: ["500 ml Pack", "1 L Pack"] },
                  { name: "Toned Milk", variantGroups: ["500 ml Pack", "1 L Pack"] },
                  "Double Toned Milk",
                  "Skimmed Milk",
                  "A2 Milk",
                  "Organic Milk",
                ],
              },
            ],
          },
          "Milk Pouches",
        ],
      },
      "Curd & Yogurt",
      "Butter",
      "Ghee",
      "Cheese",
      "Paneer & Tofu",
      "Cream",
      "Buttermilk & Lassi",
      "Condensed & Evaporated Milk",
      "Milk Powder",
      "Flavored Milk",
      "Khoya & Mawa",
      "Dairy Free Alternatives",
      "Eggs",
      "Probiotic Drinks",
      "Cream Cheese",
      "Yogurt Drinks",
      "Lassi",
      "Shrikhand",
      "Dairy Whiteners",
      "Cooking Cream",
      "Milk Sweets",
      "Curd Rice Mix",
    ],
  },
  {
    name: "Bakery",
    categories: [
      "Bread",
      "Buns & Pavs",
      "Cakes",
      "Pastries",
      "Cookies & Biscuits",
      "Rusks & Toasts",
      "Croissants",
      "Muffins & Cupcakes",
      "Doughnuts",
      "Bagels",
      "Pizza Bases",
      "Tortillas & Wraps",
      "Bakery Snacks",
      "Gluten Free Bakery",
      "Cake Decorations",
      "Khari & Puffs",
      "Cake Rusks",
      "Tea Cakes",
      "Bread Sticks",
      "Garlic Bread",
      "Burger Buns",
      "Multigrain Bread",
    ],
  },
  {
    name: "Beverages",
    categories: [
      {
        name: "Tea",
        subcategories: ["Black Tea", "Green Tea", "Herbal Tea", "Masala Tea", "Tea Bags"],
      },
      {
        name: "Coffee",
        subcategories: ["Filter Coffee", "Instant Coffee", "Ground Coffee", "Coffee Beans", "Cold Brew"],
      },
      "Health Drinks",
      "Soft Drinks",
      "Packaged Juices",
      "Fruit Drinks",
      "Energy Drinks",
      "Packaged Water",
      "Soda & Mixers",
      "Iced Tea",
      "Milkshakes",
      "Coconut Water",
      "Drink Concentrates",
      "Syrups & Squashes",
      "Kombucha & Probiotic Drinks",
      "Traditional Drinks",
      "Buttermilk Drinks",
      "Lemonade",
      "Flavored Water",
      "Sports Drinks",
      "Hot Chocolate",
      "Badam Milk",
      "Rose Milk",
      "Nannari Sharbat",
    ],
  },
  {
    name: "Snacks",
    categories: [
      "Chips & Crisps",
      "Namkeen",
      "Bhujia & Mixtures",
      "Popcorn",
      "Nachos & Dips",
      "Roasted Snacks",
      "Chocolates",
      "Candies & Toffees",
      "Biscuits",
      "Cream Biscuits",
      "Wafers",
      "Cakes & Rolls",
      "Dry Fruit Snacks",
      "Protein & Energy Bars",
      "Trail Mixes",
      "Murukku & Mixture",
      "Banana Chips",
      "Sweets & Mithai",
      "Health Snacks",
      "Imported Snacks",
    ],
  },
  {
    name: "Frozen Foods",
    attributeKeys: ["storage_type"],
    categories: [
      "Frozen Vegetables",
      "Frozen Snacks",
      "Frozen Parathas & Rotis",
      "Frozen Meat",
      "Frozen Seafood",
      "Ice Creams",
      "Frozen Desserts",
      "Frozen Fruits",
      "Ready Frozen Meals",
      "Frozen Momos & Spring Rolls",
      "French Fries",
      "Frozen Paneer Snacks",
      "Frozen Non-Veg Snacks",
      "Frozen Corn",
      "Frozen Peas",
      "Frozen Berries",
      "Frozen Kebabs",
      "Ice Cream Cones",
      "Kulfi",
      "Frozen Pizza",
      "Frozen Idli Dosa",
    ],
  },
  {
    name: "Personal Care",
    categories: [
      {
        name: "Hair Care",
        subcategories: [
          {
            name: "Shampoo",
            families: [
              {
                name: "Shampoo",
                attributeKeys: ["volume"],
                types: ["Anti-Dandruff Shampoo", "Anti-Hairfall Shampoo", "Herbal Shampoo", "Kids Shampoo", "Color Protect Shampoo"],
              },
            ],
          },
          "Conditioner",
          "Hair Oil",
          "Hair Serum",
          "Hair Color",
        ],
      },
      "Bath & Body",
      "Soap",
      "Body Wash",
      "Face Wash",
      "Face Cream & Moisturizer",
      "Oral Care",
      "Toothpaste",
      "Toothbrush",
      "Mouthwash",
      "Deodorants & Perfumes",
      "Talcum Powder",
      "Shaving & Grooming",
      "Sanitary Pads",
      "Hand Wash & Sanitizer",
      "Sunscreen",
      "Lip Care",
      "Feminine Hygiene",
      "Adult Diapers",
    ],
  },
  {
    name: "Beauty",
    attributeKeys: ["gender"],
    categories: [
      "Makeup",
      "Lipstick",
      "Foundation & Concealer",
      "Kajal & Eyeliner",
      "Mascara",
      "Nail Care & Polish",
      "Face Serums",
      "Face Masks & Packs",
      "Beauty Tools",
      "Fragrances & Perfumes",
      "Hair Styling",
      "Skin Toner",
      "Eye Care",
      "Mens Grooming",
      "Makeup Removers",
      "BB & CC Creams",
      "Bath & Body Luxury",
      "Gift Sets",
    ],
  },
  {
    name: "Health",
    categories: [
      { name: "OTC Medicines", attributeKeys: ["prescription_required"], subcategories: ["Pain Relief", "Cold & Cough", "Digestive Care", "Antacids"] },
      "Vitamins",
      "Supplements",
      "First Aid",
      "Health Devices",
      "Ayurvedic Care",
      "Homeopathy",
      "Protein & Nutrition",
      "Immunity Boosters",
      "Diabetic Care",
      "Sexual Wellness",
      "Health Monitors",
      "Sanitizers & Masks",
      "Elderly Care",
      "Eye & Ear Care",
      "Knee & Joint Care",
      "Liver Care",
      "Weight Management",
      "Skin Supplements",
      "Hair Supplements",
      "Antiseptics",
      "Thermometers",
      "Glucose & Electrolytes",
    ],
  },
  {
    name: "Baby Care",
    attributeKeys: ["age_group"],
    categories: [
      "Diapers",
      "Baby Wipes",
      "Baby Food",
      "Baby Formula",
      "Baby Skin Care",
      "Baby Bath",
      "Baby Oil & Powder",
      "Feeding Bottles",
      "Baby Accessories",
      "Baby Apparel",
      "Baby Toys",
      "Baby Health",
      "Baby Cereals",
      "Maternity Care",
      "Baby Diaper Pants",
      "Baby Lotion",
      "Baby Shampoo",
      "Baby Wash",
      "Baby Rash Cream",
      "Baby Gift Sets",
    ],
  },
  {
    name: "Pet Care",
    categories: [
      "Dog Food",
      "Cat Food",
      "Pet Treats",
      "Pet Grooming",
      "Pet Toys",
      "Pet Accessories",
      "Pet Health",
      "Aquarium Supplies",
      "Bird Food & Supplies",
      "Small Animal Supplies",
      "Pet Bedding",
      "Pet Cleaning",
      "Pet Shampoo",
      "Pet Collars & Leashes",
      "Pet Bowls",
      "Dog Chews",
      "Cat Litter",
      "Pet Vitamins",
      "Pet Carriers",
      "Pet Apparel",
    ],
  },
  {
    name: "Household",
    categories: [
      "Tissues & Napkins",
      "Garbage Bags",
      "Mosquito Repellents",
      "Shoe Care",
      "Laundry Accessories",
      "Fabric Conditioners",
      "Disposables",
      "Storage & Organizers",
      "Batteries",
      "Lighters & Matchboxes",
      "Umbrellas & Raincoats",
      "Pooja Lamp Oil",
      "Insect & Pest Control",
      "Naphthalene & Fresheners",
      "Cling Wraps & Foils",
      "Room Fresheners",
      "Toilet Rolls",
      "Kitchen Towels",
      "Pooja Candles & Diyas",
      "Household Mops",
      "Dustbins",
      "Clothes Clips",
    ],
  },
  {
    name: "Cleaning",
    categories: [
      "Detergents",
      "Dishwash",
      "Floor Cleaners",
      "Toilet Cleaners",
      "Surface Cleaners",
      "Glass Cleaners",
      "Bathroom Cleaners",
      "Kitchen Cleaners",
      "Disinfectants",
      "Scrubbers & Sponges",
      "Mops & Wipers",
      "Brooms & Brushes",
      "Buckets & Mugs",
      "Gloves & Masks",
      "Drain Cleaners",
      "Air Fresheners",
    ],
  },
  {
    name: "Kitchen",
    categories: [
      "Cookware",
      "Pressure Cookers",
      "Tawas & Pans",
      "Knives & Cutlery",
      "Kitchen Tools",
      "Storage Containers",
      "Lunch Boxes",
      "Water Bottles",
      "Dinner Sets",
      "Serveware",
      "Gas Stoves",
      "Small Kitchen Appliances",
      "Choppers & Graters",
      "Mixing Bowls",
      "Spice Boxes",
      "Casseroles",
      "Pressure Cooker Spares",
    ],
  },
  {
    name: "Electronics",
    categories: [
      "Mobiles",
      "Mobile Accessories",
      "Chargers & Cables",
      "Headphones",
      "Earbuds",
      "Power Banks",
      "Smart Watches",
      "Bluetooth Speakers",
      "Laptops",
      "Computer Accessories",
      "Memory Cards & Storage",
      "Cameras",
      "Home Appliances",
      "Kitchen Appliances",
      "Light Bulbs & Lighting",
      "Extension Boards",
      "Trimmers & Groomers",
      "Irons",
      "Fans",
      "Mixer Grinders",
    ],
  },
  {
    name: "Stationery",
    categories: [
      "Notebooks",
      "Pens",
      "Pencils",
      "Markers & Highlighters",
      "Erasers & Sharpeners",
      "Geometry Boxes",
      "Files & Folders",
      "Art Supplies",
      "Craft Materials",
      "Office Supplies",
      "Calculators",
      "Sticky Notes",
      "Glue & Adhesives",
      "School Bags",
      "Drawing Books",
      "Scales & Rulers",
      "Whiteboards",
      "Staplers & Punches",
      "Paper & Reams",
      "Envelopes",
      "Gift Wrapping",
      "Diaries & Planners",
    ],
  },
  {
    name: "Pooja",
    regions: ALL_SOUTH,
    categories: [
      "Agarbatti & Incense",
      "Camphor",
      "Pooja Oil",
      "Diyas & Lamps",
      "Cotton Wicks",
      "Kumkum & Turmeric",
      "Pooja Thali",
      "Idols & Statues",
      "Sacred Threads",
      "Dhoop & Sambrani",
      "Pooja Flowers",
      "Bells & Accessories",
      "Rangoli Colors",
      "Sandalwood Products",
      "Holy Water Pots",
      "Prayer Books",
      "Coconut for Pooja",
      "Betel Leaves & Nuts",
      "Vibhuti",
      "Chandan",
      "Garland Threads",
      "Pooja Cloth",
    ],
  },
  {
    name: "Automotive",
    categories: [
      "Car Care",
      "Bike Care",
      "Engine Oils",
      "Lubricants",
      "Car Accessories",
      "Bike Accessories",
      "Tyres & Tubes",
      "Car Electronics",
      "Helmets",
      "Cleaning Kits",
      "Car Air Fresheners",
      "Battery & Chargers",
      "Tools & Equipment",
      "Wiper Blades",
      "Seat Covers",
      "Floor Mats",
      "Horns",
      "Puncture Kits",
      "Polish & Wax",
      "Jump Starters",
      "Mobile Holders",
    ],
  },
  {
    name: "Sports",
    attributeKeys: ["gender"],
    categories: [
      "Fitness Equipment",
      "Yoga & Wellness",
      "Cricket",
      "Football",
      "Badminton",
      "Tennis",
      "Cycling",
      "Swimming",
      "Gym Accessories",
      "Sportswear",
      "Sports Shoes",
      "Outdoor & Adventure",
      "Skating",
      "Team Sports",
      "Sports Nutrition",
      "Table Tennis",
      "Basketball",
      "Volleyball",
      "Carrom & Board Games",
      "Camping Gear",
      "Fitness Trackers",
    ],
  },
  {
    name: "Fashion",
    attributeKeys: ["gender", "age_group"],
    categories: [
      { name: "Mens Clothing", subcategories: ["Shirts", "T-Shirts", "Trousers", "Jeans", "Ethnic Wear"] },
      { name: "Womens Clothing", subcategories: ["Kurtas & Kurtis", "Sarees", "Dresses", "Tops", "Leggings"] },
      "Kids Clothing",
      "Innerwear",
      "Footwear",
      "Watches",
      "Bags & Wallets",
      "Belts",
      "Sunglasses",
      "Jewellery",
      "Nightwear",
      "Winter Wear",
      "Fashion Accessories",
      "Socks",
      "Caps & Hats",
      "Handkerchiefs",
    ],
  },
  {
    name: "Home Essentials",
    categories: [
      "Bed Linen",
      "Bath Linen",
      "Curtains",
      "Cushions & Covers",
      "Door Mats",
      "Home Decor",
      "Wall Clocks",
      "Photo Frames",
      "Artificial Plants",
      "Storage Boxes",
      "Hangers",
      "Home Lighting",
      "Candles",
      "Mirrors",
      "Furnishings",
      "Carpets & Rugs",
    ],
  },
  {
    name: "Medicine",
    attributeKeys: ["prescription_required"],
    categories: [
      "Prescription Medicines",
      "Diabetes Care",
      "Cardiac Care",
      "Respiratory Care",
      "Pain Management",
      "Antibiotics",
      "Skin Treatments",
      "Eye & Ear Drops",
      "Gastro Care",
      "Womens Health",
      "Mens Health",
      "Surgical Supplies",
      "Orthopaedic Aids",
      "Medical Devices",
      "Hypertension Care",
      "Thyroid Care",
      "Neuro Care",
      "Liver & Kidney Care",
      "Vaccines & Injections",
      "Inhalers",
      "Nebulizers",
      "Wound Care",
    ],
  },
  {
    name: "Local Specialties",
    regions: ALL_SOUTH,
    categories: [
      "Handmade Pickles",
      "Home Made Snacks",
      "Local Sweets",
      "Filter Coffee Powder",
      "Traditional Masalas",
      "Country Sugar",
      "Cold Pressed Oils",
      "Millet Products",
      "Herbal Products",
      "Handloom Items",
      "Local Honey",
      "Artisan Foods",
      "Native Rice Varieties",
      "Palm Products",
      "Hand Pounded Rice",
      "Wood Pressed Oil",
      "Country Eggs",
      "Nattu Sakkarai",
      "Herbal Powders",
      "Karupatti",
      "Sun Dried Items",
      "Native Greens",
    ],
  },
  {
    name: "Regional Foods",
    regions: ALL_SOUTH,
    categories: [
      "Tamil Nadu Specials",
      "Kerala Specials",
      "Karnataka Specials",
      "Andhra Specials",
      "Telangana Specials",
      "South Indian Tiffin Items",
      "Banana Leaf Meal Kits",
      "Idli Dosa Batter",
      "Podis & Powders",
      "Authentic Regional Spices",
      "Festival Foods",
      "Traditional Sweets",
      "Pickled Vegetables",
      "Regional Beverages",
      "Sambar & Rasam Mix",
      "Filter Coffee Decoction",
      "Appalam & Vathal",
      "Coconut Chutney Mix",
      "Tamarind & Spices",
      "Millet Tiffin Mix",
      "Pickle Varieties",
      "Sweet Pongal Mix",
    ],
  },
  {
    name: "Services",
    categories: [
      "Appliance Repair",
      "Home Cleaning",
      "Pest Control",
      "Plumbing",
      "Electrician",
      "Carpentry",
      "Laundry Services",
      "Salon at Home",
      "Vehicle Service",
      "Packers & Movers",
      "Tutoring",
      "Gardening",
      "Painting",
      "Water Can Delivery",
      "Appliance Installation",
      "CCTV Installation",
      "Interior Design",
      "Massage at Home",
      "Cook at Home",
      "Errand Services",
    ],
  },
];

function asCategory(seed: CategorySeed): { name: string; attributeKeys?: string[]; subcategories?: SubcategorySeed[] } {
  return typeof seed === "string" ? { name: seed } : seed;
}

function asSubcategory(seed: SubcategorySeed): { name: string; families?: FamilySeed[] } {
  return typeof seed === "string" ? { name: seed } : seed;
}

function asType(seed: TypeSeed): { name: string; variantGroups?: string[] } {
  return typeof seed === "string" ? { name: seed } : seed;
}

/**
 * Expands {@link CANONICAL_DEPARTMENTS} into deterministic engine inputs. IDs are the hierarchical
 * slug (e.g. `dairy-milk-liquid-milk`), guaranteeing global uniqueness and stable parent links.
 */
export function buildCanonicalTaxonomyInputs(): TaxonomyNodeInput[] {
  const inputs: TaxonomyNodeInput[] = [];

  CANONICAL_DEPARTMENTS.forEach((department, departmentIndex) => {
    const departmentSlug = slugify(department.name);
    inputs.push({
      id: departmentSlug,
      level: "DEPARTMENT",
      name: department.name,
      parentId: null,
      regions: department.regions,
      attributeKeys: department.attributeKeys,
      sortOrder: departmentIndex,
    });

    asCategoryList(department.categories).forEach((category, categoryIndex) => {
      const categorySlug = `${departmentSlug}-${slugify(category.name)}`;
      inputs.push({
        id: categorySlug,
        level: "CATEGORY",
        name: category.name,
        parentId: departmentSlug,
        attributeKeys: category.attributeKeys,
        sortOrder: categoryIndex,
      });

      (category.subcategories ?? []).forEach((subSeed, subIndex) => {
        const subcategory = asSubcategory(subSeed);
        const subcategorySlug = `${categorySlug}-${slugify(subcategory.name)}`;
        inputs.push({
          id: subcategorySlug,
          level: "SUBCATEGORY",
          name: subcategory.name,
          parentId: categorySlug,
          sortOrder: subIndex,
        });

        (subcategory.families ?? []).forEach((family, familyIndex) => {
          const familySlug = `${subcategorySlug}-${slugify(family.name)}`;
          inputs.push({
            id: familySlug,
            level: "PRODUCT_FAMILY",
            name: family.name,
            parentId: subcategorySlug,
            attributeKeys: family.attributeKeys,
            sortOrder: familyIndex,
          });

          (family.types ?? []).forEach((typeSeed, typeIndex) => {
            const type = asType(typeSeed);
            const typeSlug = `${familySlug}-${slugify(type.name)}`;
            inputs.push({
              id: typeSlug,
              level: "PRODUCT_TYPE",
              name: type.name,
              parentId: familySlug,
              sortOrder: typeIndex,
            });

            (type.variantGroups ?? []).forEach((variantName, variantIndex) => {
              inputs.push({
                id: `${typeSlug}-${slugify(variantName)}`,
                level: "VARIANT_GROUP",
                name: variantName,
                parentId: typeSlug,
                sortOrder: variantIndex,
              });
            });
          });
        });
      });
    });
  });

  return inputs;
}

function asCategoryList(categories: CategorySeed[]) {
  return categories.map(asCategory);
}
